stages:
  data_ingestion:
    cmd: python "src/data_ingestion.py"
    deps:
    - "src/data_ingestion.py"
    outs:
    - "data/data_ingestion"

  data_preprocessing:
    cmd: python "src/data_preprocessing.py"
    deps:
    - "data/data_ingestion"
    - "src/data_preprocessing.py"
    outs:
    - "data/data_preprocessing"

  feature_engineering:
    cmd: python "src/feature_engineering.py"
    deps:
    - "data/data_preprocessing"
    - "src/feature_engineering.py"
    outs:
    - "data/feature_engineering"

  model_training:
    cmd: python "src/model_training.py"
    deps:
    - "data/feature_engineering"
    - "src/model_training.py"
    outs:
    - "model/model.pkl"

  model_evaluation:
    cmd: python "src/model_evaluation.py"
    deps:
    - "model/model.pkl"
    - "src/model_evaluation.py"
    outs:
    - "reports/metrics_data.json"